package top.foxball.cartask.service

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever
import org.springframework.jdbc.datasource.DriverManagerDataSource
import top.foxball.cartask.config.FileProperties
import top.foxball.cartask.config.MaintenanceGate
import top.foxball.cartask.entity.StoredFile
import top.foxball.cartask.repository.StoredFileRepository
import top.foxball.cartask.service.impl.DataBackupServiceImpl
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDateTime
import java.util.UUID
import java.util.zip.ZipFile

class DataBackupServiceImplTests {
    private fun dataSource(): DriverManagerDataSource = DriverManagerDataSource().apply {
        setDriverClassName("org.h2.Driver")
        url = "jdbc:h2:mem:backup-${UUID.randomUUID()};DB_CLOSE_DELAY=-1"
        username = "sa"
        password = ""
    }

    private fun seed(datasource: DriverManagerDataSource) {
        datasource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement.execute("create table owners (id bigint generated by default as identity primary key, name varchar(64) not null)")
                statement.execute(
                    "create table plates (id bigint generated by default as identity primary key, owner_id bigint," +
                        " number varchar(32) not null, remark varchar(64)," +
                        " constraint fk_plates_owner foreign key (owner_id) references owners(id))",
                )
                statement.execute("insert into owners (id, name) values (1, '张''三')")
                statement.execute("insert into owners (id, name) values (2, '李四')")
                statement.execute("insert into plates (id, owner_id, number, remark) values (7, 1, '京A12345', null)")
            }
        }
    }

    private fun storedFile(relativePath: String, sizeBytes: Long = 12L): StoredFile = StoredFile().apply {
        id = UUID.randomUUID()
        originalFilename = "人脸照片.jpg"
        storedFilename = "stored.jpg"
        this.relativePath = relativePath
        contentType = "image/jpeg"
        this.sizeBytes = sizeBytes
        sha256 = "0".repeat(64)
        createdAt = LocalDateTime.of(2026, 9, 13, 10, 30, 0)
        uploadedByUserId = 1
        departmentCode = "D001"
    }

    private fun service(
        datasource: DriverManagerDataSource,
        storageRoot: Path,
        files: List<StoredFile>,
        progress: BackupProgressService = BackupProgressService(),
    ): DataBackupServiceImpl {
        val repository = mock<StoredFileRepository>()
        whenever(repository.findAll()).thenReturn(files)
        whenever(repository.count()).thenReturn(files.size.toLong())
        whenever(repository.sumSizeBytes()).thenReturn(files.sumOf { it.sizeBytes })
        return DataBackupServiceImpl(
            dataSource = datasource,
            storedFileRepository = repository,
            fileProperties = FileProperties(storageRoot = storageRoot.toString(), baseUrl = "http://127.0.0.1:8080"),
            maintenanceGate = MaintenanceGate(),
            backupProgress = progress,
            auditService = null,
        )
    }

    @Test
    fun `只导出 SQL 时产出可执行的建表与插入语句`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val artifact = service(datasource, storageRoot, emptyList()).export(includeFiles = false)

        try {
            assertTrue(artifact.filename.endsWith(".sql"), "不勾选压缩包时应直接产出 SQL，实际：${artifact.filename}")
            assertEquals("application/sql", artifact.contentType)
            assertFalse(artifact.stats.archiveIncluded)

            val sql = Files.readString(artifact.path)
            assertEquals(2, artifact.stats.tableCount)
            assertEquals(3, artifact.stats.rowCount)
            assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS \"PUBLIC\".\"OWNERS\""), sql)
            assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"), "自增主键必须写成 IDENTITY，否则空库恢复时没有序列")
            assertTrue(sql.contains("\"OWNER_ID\" bigint"), "外键列定义缺失：$sql")
            assertTrue(sql.contains("CONSTRAINT \"FK_PLATES_OWNER\" FOREIGN KEY (\"OWNER_ID\") REFERENCES \"PUBLIC\".\"OWNERS\""), "外键约束缺失：$sql")
            assertTrue(sql.indexOf("\"PLATES\" (") > sql.indexOf("\"OWNERS\" ("), "被引用的表必须排在引用它的表之前，否则空库恢复时建表会失败")
            assertTrue(sql.contains("INSERT INTO \"PUBLIC\".\"OWNERS\""), sql)
            // 单引号要按 SQL 规则翻倍，否则恢复时脚本在此处直接语法中断。
            assertTrue(sql.contains("'张''三'"), "字符串里的单引号未转义：$sql")
            assertTrue(sql.contains("(7, 1, '京A12345', NULL)"), "带 NULL 的插入语句不正确：$sql")
        } finally {
            artifact.cleanupRoot.toFile().deleteRecursively()
        }
    }

    @Test
    fun `勾选压缩包时同时打包 SQL 附件与清单`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val stored = storageRoot.resolve("2026/09/13/photo.jpg")
        Files.createDirectories(stored.parent)
        Files.writeString(stored, "fake-image-bytes")
        val metadata = storedFile("2026/09/13/photo.jpg", Files.size(stored))

        val artifact = service(datasource, storageRoot, listOf(metadata)).export(includeFiles = true)

        try {
            assertTrue(artifact.filename.endsWith(".zip"), artifact.filename)
            assertEquals("application/zip", artifact.contentType)
            assertTrue(artifact.stats.archiveIncluded)
            assertEquals(1, artifact.stats.fileCount)
            assertEquals(0, artifact.stats.missingFiles)
            assertTrue(artifact.stats.sqlBytes > 0)

            ZipFile(artifact.path.toFile()).use { zip ->
                val names = zip.entries().asSequence().map { it.name }.toSet()
                assertTrue("database.sql" in names, "压缩包里必须有 SQL 备份，实际：$names")
                assertTrue("files/2026/09/13/photo.jpg" in names, "附件没有打进压缩包，实际：$names")
                assertTrue("manifest.csv" in names, "清单没有打进压缩包，实际：$names")

                val manifestBytes = zip.getInputStream(zip.getEntry("manifest.csv")).readBytes()
                assertTrue(
                    manifestBytes.size > 3 && manifestBytes[0] == 0xEF.toByte() &&
                        manifestBytes[1] == 0xBB.toByte() && manifestBytes[2] == 0xBF.toByte(),
                    "清单要带 BOM，否则 Excel 打开中文文件名是乱码",
                )
                val manifest = manifestBytes.toString(Charsets.UTF_8)
                assertTrue(manifest.contains("人脸照片.jpg"), manifest)
                assertTrue(manifest.contains(",OK"), "存在的附件应标记为 OK：$manifest")
            }
        } finally {
            artifact.cleanupRoot.toFile().deleteRecursively()
        }
    }

    @Test
    fun `物理文件缺失时记入清单而不是静默跳过`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val metadata = storedFile("2026/09/13/gone.jpg")

        val artifact = service(datasource, storageRoot, listOf(metadata)).export(includeFiles = true)

        try {
            assertEquals(0, artifact.stats.fileCount)
            assertEquals(1, artifact.stats.missingFiles)
            ZipFile(artifact.path.toFile()).use { zip ->
                val manifest = zip.getInputStream(zip.getEntry("manifest.csv")).readBytes().toString(Charsets.UTF_8)
                assertTrue(manifest.contains(",MISSING"), "缺失的附件必须在清单里标出来：$manifest")
            }
        } finally {
            artifact.cleanupRoot.toFile().deleteRecursively()
        }
    }

    @Test
    fun `越界的相对路径不会被读进备份`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val outside = storageRoot.parent.resolve("outside-secret.txt")
        Files.writeString(outside, "top-secret")
        val metadata = storedFile("../outside-secret.txt")

        try {
            val artifact = service(datasource, storageRoot, listOf(metadata)).export(includeFiles = true)
            try {
                assertEquals(1, artifact.stats.missingFiles, "逃出根目录的路径必须按缺失处理")
                assertEquals(0, artifact.stats.fileCount)
                ZipFile(artifact.path.toFile()).use { zip ->
                    val names = zip.entries().asSequence().map { it.name }.toList()
                    assertTrue(names.none { it.contains("outside-secret") }, "越界文件被打进了备份：$names")
                }
            } finally {
                artifact.cleanupRoot.toFile().deleteRecursively()
            }
        } finally {
            Files.deleteIfExists(outside)
        }
    }

    @Test
    fun `概览返回表数量与附件体量`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val summary = service(datasource, storageRoot, listOf(storedFile("a/b.jpg", 2048))).summary()

        assertEquals(2, summary.tableCount)
        assertEquals(1L, summary.fileCount)
        assertEquals(2048L, summary.fileBytes)
        assertTrue(summary.databaseProduct.contains("H2"), summary.databaseProduct)
        assertNotNull(summary.storageRoot)
    }

    @Test
    fun `导出前先统计范围，结束后进度停在完成`(@TempDir storageRoot: Path) {
        val datasource = dataSource()
        seed(datasource)
        val progress = BackupProgressService()

        val artifact = service(datasource, storageRoot, listOf(storedFile("2026/09/13/photo.jpg")), progress)
            .export(includeFiles = true)

        try {
            val snapshot = progress.snapshot()
            assertEquals(BackupPhase.FINISHED, snapshot.phase)
            assertEquals("备份完成", snapshot.label)
            assertEquals(100, snapshot.percent)
            // 范围统计要落在进度上，页面才有"共多少张表、多少行"可展示。
            assertEquals(2, snapshot.tablesTotal)
            assertEquals(2, snapshot.tablesDone)
            assertEquals(3L, snapshot.rowsTotal)
            assertEquals(3L, snapshot.rowsDone)
            // 附件元数据在册但物理文件不存在，打包阶段仍然要走完并如实计数。
            assertEquals(1, snapshot.filesTotal)
            assertEquals(1, snapshot.filesDone)
            assertNotNull(snapshot.startedAt)
            assertNotNull(snapshot.finishedAt)
        } finally {
            artifact.cleanupRoot.toFile().deleteRecursively()
        }
    }

    @Test
    fun `导出失败时进度记下停在哪个阶段`(@TempDir storageRoot: Path) {
        // 连不上的库：导出在统计范围阶段就会失败。
        val unreachable = DriverManagerDataSource().apply {
            setDriverClassName("org.h2.Driver")
            url = "jdbc:h2:tcp://127.0.0.1:1/unreachable"
            username = "sa"
            password = ""
        }
        val progress = BackupProgressService()
        val failing = service(unreachable, storageRoot, emptyList(), progress)
        var cleanupRoot: Path? = null

        // 取连接失败抛的是受检的 SQLException，进度同样必须落到 FAILED。
        assertThrows(Exception::class.java) {
            cleanupRoot = failing.export(includeFiles = false).cleanupRoot
        }

        val snapshot = progress.snapshot()
        assertEquals(BackupPhase.FAILED, snapshot.phase)
        assertNotNull(snapshot.message, "失败原因要留在进度里，否则页面上只剩一个卡住的进度条")
        cleanupRoot?.let { it.toFile().deleteRecursively() }
    }
}
